# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20170909_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
