# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20170909_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='post_body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_time',
            new_name='post_published_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='post_id'
        )

    ]
